studentg/accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

reset_patterns = [
    path('',
         auth_views.PasswordResetView.as_view(
             template_name='password_reset.html',
             email_template_name='password_reset_email.html',
             subject_template_name='password_reset_subject.txt'
         ),
         name='password_reset'),
    path('done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]
# change_password_patterns = [
#     # path('', auth_views.PasswordChangeView.as_view(template_name='accounts/view_profile.html',
#     #                                                success_url=reverse_lazy('dashboard')),
#     #      name='password_change'),
#     path('', views.CustomPasswordChangeView.as_view(), name='password_change'),
#     # path('done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
#     #      name='password_change_done'),
# ]
urlpatterns = [
    # path('signup/<uidb64>/<token>/', views.signup, name='signup'),

    #     path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),

    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('home')), name="logout"),

    path('reset/', include(reset_patterns)),

    # path('settings/password/', include(change_password_patterns)),
]

studentg/accounts/models.py
import random

import six
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.crypto import salted_hmac
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django_hosts.resolvers import reverse

from redressal.models import RedressalBody
from .constants import DesignationConstants, TempDesignationConstants


# Create your models here.


class User(DesignationConstants, AbstractUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    designation = models.CharField(max_length=5, choices=DesignationConstants.DESIGNATION_CHOICES)
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_designation_object(self):
        if self.designation == self.STUDENT:
            return self.student
        elif self.designation == self.UNIVERSITY or self.designation == self.UNI_HEAD:
            return self.universitymember
        elif self.designation == self.INSTITUTE or self.designation == self.INS_HEAD:
            return self.institutemember
        elif self.designation == self.DEPARTMENT or self.designation == self.DEP_HEAD:
            return self.departmentmember

    def get_redressal_body(self):
        return self.get_designation_object().redressal_body

    def get_body_dict(self):
        dictionary = {}
        redressal_body = self.get_redressal_body()
        if redressal_body.body_type == redressal_body.DEPARTMENT:
            dictionary['dept'] = redressal_body.name
            redressal_body = redressal_body.department.institute.redressal_body
        if redressal_body.body_type == redressal_body.INSTITUTE:
            dictionary['inst'] = redressal_body.name
            redressal_body = redressal_body.institute.university.redressal_body
        dictionary['uni'] = redressal_body.name
        return dictionary


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    redressal_body = models.ForeignKey(RedressalBody, on_delete=models.CASCADE)
    rollno = models.IntegerField()

    # class Meta:
    #     unique_together = (("redressal_body", "rollno"),)


class UniversityMember(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    redressal_body = models.ForeignKey(RedressalBody, on_delete=models.CASCADE)

    def get_body_members(self):
        return User.objects.filter(universitymember__in=self.redressal_body.universitymember_set.all()).exclude(
            pk=self.user.pk)


class InstituteMember(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    redressal_body = models.ForeignKey(RedressalBody, on_delete=models.CASCADE)

    def get_body_members(self):
        return User.objects.filter(institutemember__in=self.redressal_body.institutemember_set.all()).exclude(
            pk=self.user.pk)


class DepartmentMember(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    redressal_body = models.ForeignKey(RedressalBody, on_delete=models.CASCADE)

    def get_body_members(self):
        return User.objects.filter(departmentmember__in=self.redressal_body.departmentmember_set.all()).exclude(
            pk=self.user.pk)


class TempUser(TempDesignationConstants, models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()
    redressal_body = models.ForeignKey(RedressalBody, on_delete=models.CASCADE)

    designation = models.CharField(max_length=5, choices=TempDesignationConstants.DESIGNATION_CHOICES)
    uidb64 = models.CharField(max_length=255)
    token = models.CharField(max_length=255)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def save(self, *args, **kwargs):
        if not self.uidb64:
            self.uidb64 = urlsafe_base64_encode(
                force_bytes(six.text_type(self.pk) + six.text_type(self.created_at))[::3])
        if not self.token:
            value = six.text_type(self.email) + six.text_type(self.designation) + six.text_type(
                self.first_name) + six.text_type(self.last_name) + six.text_type(self.created_at)
            self.token = salted_hmac("%s" % (random.random()), value).hexdigest()[::3]
        super(TempUser, self).save(*args, **kwargs)

    def get_redressal_body(self):
        return self.redressal_body

    def send_mail(self):
        if self.designation == self.STUDENT:
            host = 'www'
        else:
            host = 'redressal'
        signup_relative_url = reverse('signup', host=host, kwargs={
            'uidb64': self.uidb64,
            'token': self.token
        })
        send_mail(
            'Sign Up for Student Grievance Portal',
            f'Click this link to sign up http:{signup_relative_url}',
            'st050100@gmail.com',
            [self.email],
            fail_silently=False,
        )


class StudentTempUser(models.Model):
    user = models.OneToOneField(TempUser, on_delete=models.CASCADE)
    rollno = models.IntegerField()

studentg/studentg/models.py
from django.db import models
from django.db import transaction
from django.core.mail import send_mail
from accounts.models import User
import datetime
from redressal.models import SubCategory, RedressalBody
from .constants import StatusConstants
from django_hosts.resolvers import reverse


# Concurrency controlled generation of tokens Singleton table
class DayToken(models.Model):
    counter = models.IntegerField(default=0)
    last_update = models.DateField(auto_now_add=True)

    @classmethod
    def get_new_token(cls):
        with transaction.atomic():
            daytoken = cls.objects.select_for_update().first()
            if daytoken == None:
                daytoken = cls()
            if daytoken.last_update != datetime.date.today():
                daytoken.last_update = datetime.date.today()
                daytoken.counter = 0
            daytoken.counter = daytoken.counter + 1
            daytoken.save()
            return daytoken.counter

    def save(self, *args, **kwargs):
        self.__class__.objects.exclude(id=self.id).delete()
        super(DayToken, self).save(*args, **kwargs)


class Grievance(StatusConstants, models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='grievances')
    date = models.DateField(auto_now_add=True)
    redressal_body = models.ForeignKey(RedressalBody, on_delete=models.CASCADE, related_name='grievances')
    daytoken = models.IntegerField()

    last_update = models.DateField(auto_now=True)
    status = models.PositiveSmallIntegerField(choices=StatusConstants.STATUS_CHOICES, default=StatusConstants.REVIEW)
    message = models.TextField(max_length=1000)
    subject = models.CharField(max_length=255)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    UNIVERSITY = 1
    INSTITUTE = 2
    DEPARTMENT = 3
    CATEGORY_CHOICES = [
        (UNIVERSITY, 'University'),
        (INSTITUTE, 'Institute'),
        (DEPARTMENT, 'Department'),
    ]
    category = models.PositiveSmallIntegerField(choices=CATEGORY_CHOICES)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)

    class Meta:
        unique_together = (("date", "daytoken"),)
        ordering = ['-last_update']

    def __str__(self):
        return f'{self.subject} - ({self.pk})'
    
    def token(self):
        return self.date.strftime('%Y%m%d') + str(self.daytoken).zfill(4)
    
    def status_html_class(self):
        return self.STATUS_COLORS[self.status]

    def get_escalated_level_display(self):
        escalator = {
            self.DEPARTMENT: 'Institute',
            self.INSTITUTE: 'University'
        }
        return escalator[self.category]

    @classmethod
    def get_from_token(cls, token):
        date = datetime.datetime.strptime(token[:-4], "%Y%m%d").date()
        daytoken = int(token[-4:])
        try:
            grievance = cls.objects.get(date=date, daytoken=daytoken)
        except cls.DoesNotExist:
            grievance = None
        return grievance


class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    grievance = models.ForeignKey(Grievance, on_delete=models.CASCADE, related_name='reply')
    date_time = models.DateTimeField(auto_now_add=True)
    message = models.TextField(max_length=1000)

    class Meta:
        ordering = ['date_time']
        verbose_name_plural = "Replies"


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    grievance = models.ForeignKey(Grievance, on_delete=models.CASCADE, related_name='notifications')
    date_time = models.DateTimeField(auto_now_add=True)

    def send_mail(self):
        token_no = self.grievance.token()
        url = reverse('view_grievance', host='www', kwargs={
            'token': token_no
        })
        send_mail(
            f'Your Grievance No. {token_no}',
            f'There has been some action on your grievance: click this link to check it out: http:{url}',
            'st050100@gmail.com',
            [self.user.email],
            fail_silently=False,
        )

    def redressal_send_mail(self):
        token_no = self.grievance.token()
        url = reverse('view_grievance', host='redressal', kwargs={
            'token': token_no
        })
        send_mail(
            f'New Grievance having No. {token_no}',
            f'There is a new grievance: click this link to check it out: http:{url}',
            'st050100@gmail.com',
            [self.user.email],
            fail_silently=False,
        )


class Rating(models.Model):
    grievance = models.OneToOneField(Grievance, on_delete=models.CASCADE, related_name='rating')
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    FIVE = 5
    RATING_CHOICES = [
        (FIVE, '5 Stars'),
        (FOUR, '4 Stars'),
        (THREE, '3 Stars'),
        (TWO, '2 Stars'),
        (ONE, '1 Star'),
    ]
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)

    def get_lacking_score(self):
        return 5 - self.rating

studentg/templates/includes/chart_scripts.html
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

studentg/templates/includes/iterate_grievances.html
{% for grievance in grievances %}
    <tr aria-rowspan='2' class='card-row'>
        <td class='align-middle pb-0 pt-0'>
            <div class='initiative-heading'>
                <h6 class=' mb-0' style='text-align: center'>Token Number</h6>
                <h6 class='d-xs-block d-md-none mb-0 font-weight-bold'
                    style='color:#252766; text-align: center; font-size: small !important;'>
                    {{ grievance.token }}</h6>
                <h3 class='d-none d-md-block mb-0'
                    style='text-align: center; color:#252766;'>
                    {{ grievance.token }}</h3>
            </div>
        </td>
        <td class='align-middle pb-0' colspan="2">
            <table class="table step3-table filter-this-table">
                <tr>
                    <th colspan="2" style="text-align:left;" class="p-0">
                        <h5 class='d-none d-md-block mb-0 text-uppercase font-weight-bold'
                            style='color:#252766;'>{{ grievance.subject }}</h5>
                    </th>
                </tr>
                <tr>
                    <th class="align-middle p-0">
                        <p class='m-0 d-xs-block d-md-none font-weight-bold text-uppercase'
                           style='color:#252766; font-size: small !important;'>{{ grievance.subject }}</p>
                        <p class='m-0 d-none d-md-block'
                           style="font-weight: normal !important;">
                            <b>Category:</b> {{ grievance.get_category_display }}</p>
                        <p class='m-0 d-none d-md-block'
                           style="font-weight: normal !important;">
                            <b>Sub-Category:</b> {{ grievance.sub_category }}</p>
                        <p class='m-0 d-block d-md-none'
                           style="font-weight: normal !important;"><b>Status:</b><b
                                class="{{ grievance.status_html_class }}">
                            {{ grievance.get_status_display }}</b></p>
                    </th>
                    <th class='align-middle p-0'>
                        <p class='m-0 d-none d-md-block'
                           style="font-weight: normal !important;"><b>Status:</b><span
                                class="{{ grievance.status_html_class }}">
                                                {{ grievance.get_status_display }}</span></p>
                        <p class='mb-0 d-none d-md-block'
                           style="font-weight: normal !important;"><b>Posted
                            on:</b> {{ grievance.date }}</p>
                    </th>
                </tr>
            </table>
        </td>
        <td class="pb-0" style="text-align: left;" colspan="1">
            <button type='button' class='btn btn-sm btn-outline-dark' data-toggle='collapse'
                    data-target="#collapse-grievance-{{ forloop.counter }}"
                    aria-expanded='false' aria-controls='collapseExample'>
                <i class='fa fa-angle-down' aria-hidden='true'></i>
            </button>
        </td>
        {#                            <td class='align-middle' hidden>#}
        {##}
        {#                            </td>#}
    </tr>
    <tr>
        <td colspan='4' class='sub-td'>
            <table class='collapse sub-table' id='collapse-grievance-{{ forloop.counter }}'>
                {#                                            <tr hidden>#}
                {#                                                <td colspan='1'>#}
                {#                                                    Details of Applied Volunteers#}
                {#                                                </td>#}
                {#                                                <td colspan='3'>#}
                {#                                                    <a href=''>#}
                {#                                                        <button class='btn btn-sm btn-outline-primary mt-1'>#}
                {#                                                            Download#}
                {#                                                        </button>#}
                {#                                                    </a>#}
                {#                                                </td>#}
                {#                                            </tr>#}
                <tr class='d-md-none'>
                    <td colspan='1'>
                        Token Number
                    </td>
                    <td colspan='3'>
                        <div class='initiative-description'>
                            <p class='text-muted' align='left'>{{ grievance.token }}</p>
                        </div>
                    </td>
                </tr>
                <tr class='d-md-none'>
                    <td colspan='1'>
                        Subject
                    </td>
                    <td colspan='3'>
                        <div class='initiative-description'>
                            <p class='text-muted' align='left'>{{ grievance.subject }}
                            </p>
                        </div>
                    </td>
                </tr>
                <tr class='d-md-none'>
                    <td colspan='1'>
                        Category
                    </td>
                    <td colspan='3'>
                        <div class='initiative-description'>
                            <p class='text-muted'
                               align='left'>{{ grievance.get_category_display }}
                            </p>
                        </div>
                    </td>
                </tr>
                <tr class='d-md-none'>
                    <td colspan='1'>
                        Subcategory
                    </td>
                    <td colspan='2'>
                        <div class='initiative-description'>
                            <p class='text-muted' align='left'>{{ grievance.sub_category }}
                            </p>
                        </div>
                    </td>
                </tr>
                <tr class='d-md-none'>
                    <td colspan='1'>
                        Date
                    </td>
                    <td colspan='2'>
                        <div class='initiative-description'>
                            <p class='text-muted' align='left'>{{ grievance.date }}
                            </p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan='1'>
                        <p class=''>Description</p>
                    </td>
                    <td colspan='2'>
                        <div class='initiative-description'>
                            <p class='text-muted' align='left'>
                                {{ grievance.message }}
                            </p>
                        </div>
                    </td>
                </tr>
                {% if grievance.image %}
                    <tr>
                        <td colspan='1'>
                            <p class=''>Image</p>
                        </td>
                        <td colspan='2'>
                            <img src="{{ grievance.image.url }}" height="100%" width="100%">
                        </td>
                    </tr>
                {% endif %}
                <tr class='d-md-none'>
                    <td colspan='1'>
                        <p class=''>Status</p>
                    </td>
                    <td colspan='2'>
                        <div class='initiative-description'>
                            <p class="{{ grievance.status_html_class }}"
                               align='left'>{{ grievance.get_status_display }}
                            </p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan='1'>
                        <p class=''></p>
                    </td>
                    <td colspan='3'>
                        <div style='' class=' mb-2 '>
                            <button type='button' class='btn btn-primary mt-1 view-message-btn' data-url="{% url 'view_messages' grievance.token %}">
                                <i
                                style=' font-size: small'
                                class='fa fa-envelope'
                                aria-hidden='true'></i>&nbsp;Messages
                            </button>
                            {% if grievance.status == grievance.DRAFT %}
                                <a href="{% url 'edit_grievance' grievance.token %}">
                                    <button class='btn btn-dark mt-1 ml-2'><i
                                            style=' font-size: small'
                                            class='fa fa-pencil'
                                            aria-hidden='true'></i>&nbsp;Edit Draft
                                    </button>
                                </a>
                            {% endif %}
                            <a href='#'>
                                <button class='btn btn-success mt-1 ml-2'><i
                                        style=' font-size: small'
                                        class='fa fa-check'
                                        aria-hidden='true'></i>&nbsp;Approve
                                </button>
                            </a>
                            <a href='#'>
                                <button class='btn btn-danger mt-1 ml-2'><i
                                        style=' font-size: small'
                                        class='fa fa-times'
                                        aria-hidden='true'></i>&nbsp;Disapprove
                                </button>
                            </a>

                        </div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
{% endfor %}

studentg/templates/includes/iterate_replies.html
{% for reply in replies %}
<tr>
    <td style="vertical-align: middle; border-top: none !important;" colspan="1">
        <table class="table filter-this-table mb-0">
            <tr>
                <td style="padding: 4px; border-top: none !important;">
                    <h6 class="my-2 font-weight-bold">{% if reply.user == request.user %}
                        You
                        {% else %}
                        {{ reply.user.get_designation_display }}
                        {% endif %}</h6>
                </td>
                <td style="padding: 4px; text-align: right; border-top: none !important;">
                    <h6 class="my-2">{{ reply.date_time }}</h6>
                </td>
            </tr>
        </table>
        <p>
            {{ reply.message }}
        </p>
    </td>
</tr>
{% empty %}
<tr>
    <td style="vertical-align: middle; border-top: none !important;" colspan="1">
        <table class="table filter-this-table mb-0">
            <tr>
                <td style="padding: 4px; border-top: none !important;">
                    <h6 class="my-2" style="text-align: center;">No Messages to display!</h6>
                </td>
            </tr>
        </table>
    </td>
</tr>
{% endfor %}

studentg/templates/includes/pagination.html
{% load templatehelpers %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.number > 1 %}
            <li class="page-item">
                <a class="page-link" href="{% relative_url 1 'page' request.GET.urlencode %}">First</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">First</span>
            </li>
        {% endif %}

        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="{% relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Previous</span>
            </li>
        {% endif %}

        {% for page_num in paginator.page_range %}
            {% if page_obj.number == page_num %}
                <li class="page-item active">
            <span class="page-link">
                {{ page_num }}
                <span class="sr-only">(current)</span>
            </span>
                </li>
            {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link"
                       href="{% relative_url page_num 'page' request.GET.urlencode %}">{{ page_num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                   href="{% relative_url page_obj.next_page_number 'page' request.GET.urlencode %}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Next</span>
            </li>
        {% endif %}

        {% if page_obj.number != paginator.num_pages %}
            <li class="page-item">
                <a class="page-link" href="{% relative_url paginator.num_pages 'page' request.GET.urlencode %}">Last</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Last</span>
            </li>
        {% endif %}
        {#        <li class="page-item">#}
        {#            <a class="page-link text-dark" href="#" aria-label="Previous">#}
        {#                <span aria-hidden="true">&laquo;</span>#}
        {#                <span class="sr-only">Previous</span>#}
        {#            </a>#}
        {#        </li>#}
        {#        <li class="page-item active"><a class="page-link text-light" href="#">1</a></li>#}
        {#        <li class="page-item"><a class="page-link text-dark" href="#">2</a></li>#}
        {#        <li class="page-item"><a class="page-link text-dark" href="#">3</a></li>#}
        {#        <li class="page-item"><a class="page-link text-dark" href="#">4</a></li>#}
        {#        <li class="page-item">#}
        {#            <a class="page-link text-dark" href="#" aria-label="Next">#}
        {#                <span aria-hidden="true">&raquo;</span>#}
        {#                <span class="sr-only">Next</span>#}
        {#            </a>#}
        {#        </li>#}
    </ul>
</nav>

studentg/templates/includes/partial_footer.html
<footer class="footer" style="font-size: xx-small">
    <div class="container">
        <div class="row row-grid align-items-center mb-5">
            <div class="col-lg-6">
                <h3 class="text-primary font-weight-light mb-2"></h3>
                <h4 class="mb-0 font-weight-light" hidden>Let's get in touch on any of these platforms.</h4>
            </div>
            <div class="col-lg-6 text-lg-center btn-wrapper mt-3">
                <button target="_blank" onclick="window.location='https://twitter.com/';"
                        class="btn btn-icon-only btn-twitter rounded-circle">
                    <span class="btn-inner--icon"><i class="fa fa-twitter"></i></span>
                </button>
                <button target="_blank" onclick="window.location='https://facebook.com/U';"
                        class="btn-icon-only rounded-circle btn btn-facebook">
                    <span class="btn-inner--icon"><i class="fa fa-facebook"></i></span>
                </button>
                <button target="_blank" onclick="window.location='https://instagram.com/';"
                        class="btn btn-icon-only btn-instagram rounded-circle">
                    <span class="btn-inner--icon"><i class="fa fa-instagram"></i></span>
                </button>
            </div>
        </div>
        <hr>
        <div class="row align-items-center justify-content-md-between mb-3">
            <div class="col-md-6 order-1 order-lg-0">
                <div class="copyright">
                    Copyright &copy; 2020 Govt. of Andhra Pradesh<a href="#" target="_blank" hidden>Govt. of AP</a>
                </div>
            </div>
            <div class="col-md-6 order-0 order-lg-1">
                <ul class="nav nav-footer justify-content-lg-end justify-content-start mb-3">
                    <li class="nav-item">
                        <select onchange="doGTranslate(this);" style="border-radius: 5px; padding: 8px 16px !important; ::ms-expand{ display: none}; -webkit-appearance: none;
    -moz-appearance: none;
    text-indent: 1px;
    text-overflow: ''; border: none; cursor: pointer; background-color: lightgrey">
                            <option class="lang notranslate" value="en|en">English</option>
                            <option class="lang notranslate" value="en|te">తెలుగు</option>
                            <option class="lang notranslate" value="en|hi">हिन्दी</option>
                            <option class="lang notranslate" value="en|mr">मराठी</option>
                            <option class="lang notranslate" value="en|ur">اردو</option>
                            <option class="lang notranslate" value="en|fa">فارسی</option>
                            <option class="lang notranslate" value="en|bn">বাংলা</option>
                            <option class="lang notranslate" value="en|gu">ગુજરાતી</option>
                            <option class="lang notranslate" value="en|kn">ಕನ್ನಡ</option>
                            <option class="lang notranslate" value="en|ne">नेपाली</option>
                            <option class="lang notranslate" value="en|pa">ਪੰਜਾਬੀ</option>
                            <option class="lang notranslate" value="en|ta">தமிழ்</option>
                            <option class="lang notranslate" value="en|ar">ﻋﹷﺮﹶﺑﹻﻲ</option>
                        </select>
                    </li>
                    <li class="nav-item">
                        {% comment %} TODO {% endcomment %}
                        <a href="#" class="nav-link">Terms of Service</a>
                    </li>
                    <li class="nav-item">
                        {% comment %} TODO {% endcomment %}
                        <a href="#" class="nav-link">Privacy Policy</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<script src="https://account.snatchbot.me/script.js"></script><script>window.sntchChat.Init(123887)</script>

studentg/templates/includes/reply_form.html
{% load widget_tweaks %}
<div class="row form-group my-3 ">
    {% render_field reply_form.message class="form-control"%}
    {% for error in reply_form.message.errors %}
            <div class="alert alert-danger small mt-2 w-100" role="alert">
                <p> {{ error }} </p>
            </div>
    {% endfor %}
</div>